name: Java CI with Gradle

# The pipeline triggers on every push to main, master and dependability-projexxt
on:
  push:
    branches: [ "main", "master", "dependability-project" ]
  pull_request:
    branches: [ "main", "master" ]


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    # Get the souce code from repository
      - name: Checkout source code
        uses: actions/checkout@v4
    # setup java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
    # grant execute permission to Gradle wrapper
      - name: Grant exectute permission for gradlew
        run: chmod +x gradlew


    # Build the project and run the test suite
      - name: Build with Gradle
        run: ./gradlew build

    # Continuous Delivery (CD) save .jar on GitHub
      - name: Upload executable artifact (CD)
        uses: actions/upload-artifact@v4
        with:
          name: ju2jmh-executable
          path: '**/build/libs/*.jar'


      - name: Download OpenJML (Linux)
        run: |
          wget https://github.com/OpenJML/OpenJML/releases/download/21-0.23/openjml-ubuntu-22.04-21-0.23.zip -O openjml.zip
          unzip openjml.zip -d openjml_tool

      - name: Verify JML Contracts
        run: |
          JARS=$(find ~/.gradle/caches/ -name "*.jar" | tr '\n' ':')
          

          CP="converter/build/classes/java/main:$JARS"
          ./openjml_tool/openjml -esc -cp "$CP" converter/src/main/java/se/chalmers/ju2jmh/Converter.java || true
